# Generated by Django 4.2.20 on 2025-04-10 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('user', models.OneToOneField(limit_choices_to={'user_type': 'company'}, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='company_profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User Account')),
                ('company_name', models.CharField(db_index=True, max_length=255, verbose_name='Company Name')),
                ('company_registration_number', models.CharField(blank=True, max_length=30, verbose_name='Company Registration Number')),
                ('company_vat_number', models.CharField(blank=True, max_length=50, verbose_name='VAT Number')),
                ('legal_address', models.CharField(blank=True, max_length=255, verbose_name='Legal Address')),
                ('legal_city', models.CharField(blank=True, max_length=150, verbose_name='Legal City')),
                ('legal_zip_code', models.CharField(blank=True, max_length=20, verbose_name='Legal Zip Code')),
                ('legal_country', models.CharField(blank=True, max_length=150, verbose_name='Legal Country')),
                ('company_phone', models.CharField(blank=True, max_length=30, verbose_name='Company Phone')),
                ('company_email', models.EmailField(blank=True, max_length=254, verbose_name='Company Email')),
                ('contact_person', models.CharField(blank=True, max_length=255, verbose_name='Contact Person')),
                ('contact_person_phone', models.CharField(blank=True, max_length=30, verbose_name='Contact Person Phone')),
                ('contact_person_email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Person Email')),
                ('contact_person_position', models.CharField(blank=True, max_length=100, verbose_name='Contact Person Position')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profiles',
                'ordering': ['company_name'],
            },
        ),
    ]
