# Generated by Django 4.2.20 on 2025-04-23 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
        ('partner', '0006_auto_20200724_0909'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['name'], 'verbose_name': 'Partner', 'verbose_name_plural': 'Partners'},
        ),
        migrations.AlterModelOptions(
            name='stockrecord',
            options={'verbose_name': 'Partner Stock Record', 'verbose_name_plural': 'Partner Stock Records'},
        ),
        migrations.AlterUniqueTogether(
            name='stockrecord',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='partner',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, help_text='Date when the partner profile was last updated.'),
        ),
        migrations.AddField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, help_text='Partner description.', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='partner',
            name='joined_date',
            field=models.DateTimeField(auto_now_add=True, help_text='Date when the partner joined.', null=True, verbose_name='Joined Date'),
        ),
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload a logo for the partner.', null=True, upload_to='partner_logos/', verbose_name='Logo'),
        ),
        migrations.AddField(
            model_name='partner',
            name='return_policy',
            field=models.TextField(blank=True, help_text='Partner return policy.', null=True, verbose_name='Return Policy'),
        ),
        migrations.AddField(
            model_name='partner',
            name='user',
            field=models.OneToOneField(blank=True, help_text='User associated with this partner.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='partner_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partner',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', help_text='Status of partner verification.', max_length=20, verbose_name='Verification Status'),
        ),
        migrations.AddField(
            model_name='partner',
            name='website',
            field=models.URLField(blank=True, help_text='Partner website URL.', null=True, verbose_name='Website'),
        ),
        migrations.AddField(
            model_name='stockrecord',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_records', to='locations.warehouse', verbose_name='Warehouse'),
        ),
    ]
