# Generated by Django 4.2.20 on 2025-04-29 05:45

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0007_alter_partner_options_alter_stockrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='default_locattion',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, help_text='Default location of the partner.', null=True, srid=4326, verbose_name='Default Location'),
        ),
    ]
