# Generated by Django 4.2.20 on 2025-04-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_partner_default_locattion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partner',
            old_name='default_locattion',
            new_name='default_location',
        ),
    ]
