# Generated by Django 4.2.20 on 2025-04-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0028_alter_product_options_product_partner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='partner',
        ),
    ]
