# Generated by Django 4.2.20 on 2025-04-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0029_remove_product_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-date_created'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddField(
            model_name='product',
            name='condition',
            field=models.CharField(choices=[('new', 'New'), ('used', 'Used'), ('slightly_damaged', 'Slightly Damaged'), ('damaged', 'Damaged')], default='new', max_length=20, verbose_name='Condition'),
        ),
    ]
