# Generated by Django 4.2.20 on 2025-04-17 10:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='default_location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, help_text='Approximate geographic coordinates automatically determined from the location name.', null=True, srid=4326, verbose_name='Default Location Coordinates'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='default_location_name',
            field=models.CharField(blank=True, help_text='Name of the default location where items are located if no specific warehouse is used. e.g. Kaunas, Kauno rajonas.', max_length=255, verbose_name='Default Location Name'),
        ),
    ]
